objects/StudentForm__c.object
<CustomObject>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <label>MaritalStatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>UnMarried</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>StudentForm</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StudentForms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testStudentFormPdfPageClass.cls
@isTest
private class testStudentFormPdfPageClass
  {  
     static testmethod void teststudentFormPdfPageClass()
   {            
        StudentForm__c objS = new StudentForm__c();
        objS.Name = 'test student';
        objS.MaritalStatus__c = 'None';
        insert objS; 
                      
        apexpages.currentpage().getparameters().put('id',objS.id);            
        studentFormPdfPageClass sfc = new studentFormPdfPageClass();   
        sfc.change();
        sfc.getRen();           
   }
       
        static testmethod void teststudentFormPdfPageClass1()
       {            
            StudentForm__c objS = new StudentForm__c();
            objS.Name = 'test student';
            objS.MaritalStatus__c = 'Married';
            insert objS; 
            
                                  
            apexpages.currentpage().getparameters().put('id',objS.id);            
            studentFormPdfPageClass sfc = new studentFormPdfPageClass();   
            sfc.change();
            sfc.getRen();           
       }
  }