objects/StudentForm__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CollegeName__c</fullName>
        <label>CollegeName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateOfBirth__c</fullName>
        <label>DateOfBirth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hyderabad</fullName>
                </value>
                <value>
                    <fullName>Banglore</fullName>
                </value>
                <value>
                    <fullName>Chennai</fullName>
                </value>
                <value>
                    <fullName>Pune</fullName>
                </value>
                <value>
                    <fullName>KolKatta</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Mumbai</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <label>MaritalStatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>UnMarried</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PhoneNumber__c</fullName>
        <label>PhoneNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <label>Qualification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>M.Tech</fullName>
                </value>
                <value>
                    <fullName>Msc</fullName>
                </value>
                <value>
                    <fullName>B.Tech</fullName>
                </value>
                <value>
                    <fullName>Bsc</fullName>
                </value>
                <value>
                    <fullName>Bcom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>StudentForm</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StudentForms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/studentFormPdfPageClass.cls
//This is class for Displayng PDF page to user
public with sharing class studentFormPdfPageClass
{
    public boolean ren;
    public boolean getRen() {
        return ren;
    }
    public void change()
    {  
    //Comparison MaritalStatus Field wth Null if satisfied change the render property  
    if ( objS.MaritalStatus__c == 'None')      
    ren = False;
    else
    ren = True;
    system.debug('$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'+ objS.MaritalStatus__c); 
    
        
    }     
//Declaring properties 
    public StudentForm__c objS{get;set;}    
    string id1;
//Constructor For Displaying data    
    public studentFormPdfPageClass() 
    
    {
//Getting id from page 
     id1=apexpages.currentpage().getparameters().get('id');
//Checking the id 
     if(id1!=null)
      {
      objS = new StudentForm__c();
      objS=[select id,Name,Location__c,Age__c,DateOfBirth__c,Gender__c,MaritalStatus__c,PhoneNumber__c,Qualification__c,Skills__c,CollegeName__c from StudentForm__c where id=:id1];   
      }
//Checking for displaying image on page
      if ( objS.MaritalStatus__c == '')      
         ren = False;
         else
         ren = True;    
    }
 
}