objects/StudentForm__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DateOfBirth__c</fullName>
        <label>DateOfBirth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <label>MaritalStatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>UnMarried</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PhoneNumber__c</fullName>
        <label>PhoneNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <label>Qualification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>M.Tech</fullName>
                </value>
                <value>
                    <fullName>Msc</fullName>
                </value>
                <value>
                    <fullName>B.Tech</fullName>
                </value>
                <value>
                    <fullName>Bsc</fullName>
                </value>
                <value>
                    <fullName>Bcom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>StudentForm</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StudentForms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/studentFormExcelclass.cls
//this class for Displaying data in PageBlockTable
public with sharing class studentFormExcelclass
{
    //this is method for performing action when clicking the button
    public PageReference excel() {
        //This statement states that page is redirecting to excel sheet
        return new pagereference('/apex/StudentFormExcelSheet');
    }   
     //This list hold the all the StudentForm__c data 
     public List<StudentForm__c> lstS = new List<StudentForm__c>();
     //This method for getting all StudentForm__c data into the List
     public List<StudentForm__c> getGetRecords()
      {
        lstS = [select id,name,PhoneNumber__c,Qualification__c,Age__c,DateOfBirth__c,MaritalStatus__c,Gender__c,Skills__c from StudentForm__c];
        return lstS;
      }

}